### ISSUE TITLE
Issue of driver

### ISSUE THREAD

**Issue by yulan0215** [maciej-3/pp_alvium_driver#2]
Hello：
I am sorry that I encountered a problem of the driver, I used Jetson Nano with ROS system 18.04. The default python file is python 3.6.
The problem was that I could not get the image when I launch the *.launch file.   
I think the problem should be the version of the python and cv_bridge. 
Could u please give me any idea about it? Thx
Best regards
Yu Lan

**Comment by yulan0215** [comment]
I am sorry I encountered another problem, is there any code for triggering?

**Comment by maciej-3** [comment]
Hi there! I use ROS Noetic on Ubuntu 20.04 which both by default use python3. I am aware that if you use older versions of ROS, there will be some problems with this package as the older ROS versions rely on python2.

Regarding the triggering, there are no triggering options in this driver.
